#!/usr/bin/env python3
"""embed.py - build-time asset embedding (04 doc section 4.3).

Generates:
  src/embedded_lua.c  - lua/*.lua as C string table (dependency order fixed)
  src/embedded_font.c - primary TTF as C byte array

usage: embed.py <lua_dir> <font_ttf> <out_lua.c> <out_font.c>
Both outputs are build artifacts (gitignored). Runtime prefers embedded lua;
`cooloo gui --lua-dev <dir>` loads from disk instead (hot reload, see luabind.c).
"""
import os
import sys

# dependency order: chat/ui/input define globals used by main
LUA_ORDER = ["chat.lua", "ui.lua", "input.lua", "main.lua"]


def c_escape_string(data: bytes) -> str:
    out = []
    for line in data.split(b"\n"):
        s = line.decode("utf-8", "surrogateescape")
        s = s.replace("\\", "\\\\").replace('"', '\\"')
        out.append('"%s\\n"' % s)
    return "\n".join(out[:-1]) if out else '""'


def gen_lua(lua_dir: str, out_path: str):
    names = [n for n in LUA_ORDER if os.path.isfile(os.path.join(lua_dir, n))]
    names += sorted(n for n in os.listdir(lua_dir)
                    if n.endswith(".lua") and n not in LUA_ORDER)
    parts = ["/* generated by tools/embed.py - do not edit */",
             "struct embedded_lua { const char *name; const char *src; };",
             "const struct embedded_lua cooloo_embedded_lua[] = {"]
    for n in names:
        with open(os.path.join(lua_dir, n), "rb") as f:
            data = f.read()
        parts.append('{"%s",\n%s},' % (n, c_escape_string(data)))
    parts.append("};")
    parts.append("const int cooloo_embedded_lua_count = %d;" % len(names))
    with open(out_path, "w") as f:
        f.write("\n".join(parts) + "\n")
    print("embed: %s <- %s (%d scripts)" % (out_path, lua_dir, len(names)))


def gen_font(font_path: str, out_path: str):
    with open(font_path, "rb") as f:
        data = f.read()
    parts = ["/* generated by tools/embed.py - do not edit */",
             "const unsigned char cooloo_embedded_font[] = {"]
    for i in range(0, len(data), 16):
        parts.append(",".join("0x%02x" % b for b in data[i:i + 16]) + ",")
    parts.append("};")
    parts.append("const unsigned int cooloo_embedded_font_len = %d;" % len(data))
    with open(out_path, "w") as f:
        f.write("\n".join(parts) + "\n")
    print("embed: %s <- %s (%d bytes)" % (out_path, font_path, len(data)))


def main():
    if len(sys.argv) != 5:
        print(__doc__)
        return 2
    gen_lua(sys.argv[1], sys.argv[3])
    gen_font(sys.argv[2], sys.argv[4])
    return 0


if __name__ == "__main__":
    sys.exit(main())
